# railway.toml - Конфигурация для развертывания на Railway

[build]
builder = "nixpacks"
buildCommand = "npm install"

[deploy]
startCommand = "npm run db:migrate && npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
PORT = "${{PORT}}"

# Railway автоматически предоставит DATABASE_URL для PostgreSQL
# JWT_SECRET нужно будет установить вручную в Railway Dashboard